<a href="https://colab.research.google.com/github/ROARMarketingConcepts/Recurrent-Neural-Network-Examples/blob/master/Dynamic_RNN_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals

# Common imports
import numpy as np
import os

# to make this notebook's output stable across runs
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = "rnn"

def save_fig(fig_id, tight_layout=True):
    path = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID, fig_id + ".png")
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format='png', dpi=300)

In [0]:
import tensorflow as tf

In [0]:
n_steps = 2
n_inputs = 3
n_neurons = 5

In [6]:
reset_graph()

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32)

Instructions for updating:
This class is equivalent as tf.keras.layers.SimpleRNNCell, and will be replaced by that in Tensorflow 2.0.


In [0]:
init = tf.global_variables_initializer()

In [0]:
X_batch = np.array([
        [[0, 1, 2], [9, 8, 7]], # instance 1
        [[3, 4, 5], [0, 0, 0]], # instance 2
        [[6, 7, 8], [6, 5, 4]], # instance 3
        [[9, 0, 1], [3, 2, 1]], # instance 4
    ])

with tf.Session() as sess:
    init.run()
    outputs_val = outputs.eval(feed_dict={X: X_batch})

In [11]:
outputs_val  # tensor of dimension (4,2,4)

array([[[-0.85115266,  0.87358344,  0.5802911 ,  0.8954789 ,
         -0.0557505 ],
        [-0.9999959 ,  0.9999958 ,  0.9981815 ,  1.        ,
          0.37679607]],

       [[-0.9983293 ,  0.9992038 ,  0.98071444,  0.999985  ,
          0.25192663],
        [-0.7081804 , -0.07723374, -0.8522789 ,  0.5845349 ,
         -0.78780943]],

       [[-0.9999826 ,  0.99999535,  0.9992863 ,  1.        ,
          0.5159072 ],
        [-0.9993955 ,  0.99840957,  0.83422637,  0.99999976,
         -0.47325206]],

       [[ 0.8788859 ,  0.07356028,  0.97216916,  0.9998546 ,
         -0.7351168 ],
        [-0.91345143,  0.36009565,  0.7624866 ,  0.99817705,
          0.80142   ]]], dtype=float32)

### Suppose we have inputs of varying sequence lengths (i.e., sentences)

In [0]:
n_steps = 2
n_inputs = 3
n_neurons = 5

reset_graph()

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)

In [0]:
seq_length = tf.placeholder(tf.int32, [None])
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32,sequence_length=seq_length)

In [0]:
init = tf.global_variables_initializer()

In [0]:
X_batch = np.array([
        # step 0     step 1
        [[0, 1, 2], [9, 8, 7]], # instance 1
        [[3, 4, 5], [0, 0, 0]], # instance 2 (padded with zero vectors)
        [[6, 7, 8], [6, 5, 4]], # instance 3
        [[9, 0, 1], [3, 2, 1]], # instance 4
    ])

seq_length_batch = np.array([2, 1, 2, 2])   # specify the sequence length for each instance

In [0]:
with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run([outputs, states], feed_dict={X: X_batch, seq_length: seq_length_batch})

In [26]:
print(outputs_val)  

[[[-0.9123188   0.16516446  0.5548655  -0.39159346  0.20846416]
  [-1.          0.95672596  0.99831694  0.99970174  0.96518576]]

 [[-0.9998612   0.6702289   0.9723653   0.6631046   0.74457586]
  [ 0.          0.          0.          0.          0.        ]]

 [[-0.9999998   0.8967998   0.9986295   0.9647514   0.93661994]
  [-0.9999526   0.96819544  0.9600285   0.98706263  0.85459226]]

 [[-0.96435434  0.995016   -0.36150697  0.9983377   0.99949706]
  [-0.9613586   0.9568762   0.7132288   0.97729224 -0.0958299 ]]]


In [27]:
print(states_val) # [[t=1],[t=0],[t=1],[t=1]]

[[-1.          0.95672596  0.99831694  0.99970174  0.96518576]
 [-0.9998612   0.6702289   0.9723653   0.6631046   0.74457586]
 [-0.9999526   0.96819544  0.9600285   0.98706263  0.85459226]
 [-0.9613586   0.9568762   0.7132288   0.97729224 -0.0958299 ]]
